FROM mcascone/mindmap-image

ARG SOURCE_FILENAME=BitOps_Ecosystem
ARG IMPORT_FILENAME=${SOURCE_FILENAME}.md
ARG EXPORT_FILENAME=${SOURCE_FILENAME}.html
ARG EXPORT_PATH=/usr/share/nginx/html/index.html

WORKDIR /temp
COPY $IMPORT_FILENAME .
RUN npx markmap-cli $IMPORT_FILENAME

RUN cp $EXPORT_FILENAME $EXPORT_PATH

EXPOSE 80
